ORG-3: Time logs table
IvansMuzicenko/QUASAR-OrganeasyApp pull request #2
Opened 2023-02-12 09:41 UTC by IvansMuzicenko

2023-02-13 18:37 UTC, AlMuz commented on src/components/common/layout/parts/TimeLogTable.vue
> +        v-for="l in 97"
Create "97" as a variable and move to the data property, write comments to not forget what this number means and how it's being calculated

2023-02-13 19:00 UTC, AlMuz requested changes

2023-02-14 15:24 UTC, IvansMuzicenko commented on src/pages/TimeLog.vue
> +    isToday(dayOfWeek) {
Don't want to do this, because only applicable in this page for 2 components. For now I do not see reason for this

2023-02-14 15:24 UTC, IvansMuzicenko commented on src/components/common/layout/parts/TimeLogTable.vue
> +          :ref="i + '' + l"
Unused ref assigning removed

2023-02-16 17:44 UTC, merged